INSERT INTO public.discovery_keywords (term, group_name, segment, sources) VALUES
('representantes comerciais','REPRESENTANTES',NULL,'{whatsapp_group}'),
('representantes comerciais alimentos','REPRESENTANTES',NULL,'{whatsapp_group}'),
('representantes café','REPRESENTANTES',NULL,'{whatsapp_group}'),
('vendedores externos','REPRESENTANTES',NULL,'{whatsapp_group}'),
('vendedores de café','REPRESENTANTES',NULL,'{whatsapp_group}'),
('distribuidores de café','REPRESENTANTES',NULL,'{whatsapp_group}'),
('representantes supermercados','REPRESENTANTES',NULL,'{whatsapp_group}'),
('representantes food service','REPRESENTANTES',NULL,'{whatsapp_group}'),
('afiliados','AFILIADOS',NULL,'{whatsapp_group}'),
('afiliados brasil','AFILIADOS',NULL,'{whatsapp_group}'),
('afiliados café','AFILIADOS',NULL,'{whatsapp_group}'),
('afiliados tiktok shop','AFILIADOS',NULL,'{whatsapp_group}'),
('afiliados shopee','AFILIADOS',NULL,'{whatsapp_group}'),
('afiliados mercado livre','AFILIADOS',NULL,'{whatsapp_group}'),
('afiliados amazon','AFILIADOS',NULL,'{whatsapp_group}'),
('criadores afiliados','AFILIADOS',NULL,'{whatsapp_group}'),
('vendedores online','AFILIADOS',NULL,'{whatsapp_group}'),
('café','CAFÉ',NULL,'{whatsapp_group}'),
('café especial','CAFÉ',NULL,'{whatsapp_group}'),
('cafeterias','CAFÉ',NULL,'{whatsapp_group}'),
('donos de cafeteria','CAFÉ',NULL,'{whatsapp_group}'),
('baristas','CAFÉ',NULL,'{whatsapp_group}'),
('comerciantes de café','CAFÉ',NULL,'{whatsapp_group}'),
('revendedores de café','CAFÉ',NULL,'{whatsapp_group}'),
('atacado de café','CAFÉ',NULL,'{whatsapp_group}'),
('distribuição de café','CAFÉ',NULL,'{whatsapp_group}'),
('donos de mercado','VAREJO',NULL,'{whatsapp_group}'),
('supermercados são paulo','VAREJO',NULL,'{whatsapp_group}'),
('varejo alimentar','VAREJO',NULL,'{whatsapp_group}'),
('compradores supermercado','VAREJO',NULL,'{whatsapp_group}'),
('atacadistas','VAREJO',NULL,'{whatsapp_group}'),
('conveniência','VAREJO',NULL,'{whatsapp_group}'),
('mercearias','VAREJO',NULL,'{whatsapp_group}'),
('minimercados','VAREJO',NULL,'{whatsapp_group}'),
('padarias','FOOD SERVICE',NULL,'{whatsapp_group}'),
('donos de padaria','FOOD SERVICE',NULL,'{whatsapp_group}'),
('food service','FOOD SERVICE',NULL,'{whatsapp_group}'),
('bares e restaurantes','FOOD SERVICE',NULL,'{whatsapp_group}'),
('restaurantes são paulo','FOOD SERVICE',NULL,'{whatsapp_group}'),
('distribuidores food service','FOOD SERVICE',NULL,'{whatsapp_group}'),
('comércio jundiaí','REGIONAL',NULL,'{whatsapp_group}'),
('comércio campinas','REGIONAL',NULL,'{whatsapp_group}'),
('comércio sorocaba','REGIONAL',NULL,'{whatsapp_group}'),
('empreendedores jundiaí','REGIONAL',NULL,'{whatsapp_group}'),
('empreendedores campinas','REGIONAL',NULL,'{whatsapp_group}'),
('empreendedores sorocaba','REGIONAL',NULL,'{whatsapp_group}'),
('distribuidora de café','Distribuidoras','distribuidora','{google_places}'),
('distribuidora de alimentos','Distribuidoras','distribuidora','{google_places}'),
('distribuidora de produtos alimentícios','Distribuidoras','distribuidora','{google_places}'),
('distribuidora food service','Distribuidoras','distribuidora','{google_places}'),
('distribuidora de bebidas','Distribuidoras','distribuidora','{google_places}'),
('distribuidora de mercearia','Distribuidoras','distribuidora','{google_places}'),
('distribuidora de secos e molhados','Distribuidoras','distribuidora','{google_places}'),
('distribuidora de produtos para padaria','Distribuidoras','distribuidora','{google_places}'),
('distribuidora de insumos para panificação','Distribuidoras','distribuidora','{google_places}'),
('distribuidora horeca','Distribuidoras','distribuidora','{google_places}'),
('distribuidora para restaurantes','Distribuidoras','distribuidora','{google_places}'),
('distribuidora para hotéis','Distribuidoras','distribuidora','{google_places}'),
('distribuidora para cafeterias','Distribuidoras','distribuidora','{google_places}'),
('distribuidora para padarias','Distribuidoras','distribuidora','{google_places}'),
('distribuidora para cozinhas industriais','Distribuidoras','distribuidora','{google_places}'),
('fornecedor de café','Distribuidoras','distribuidora','{google_places}'),
('fornecedor de alimentos','Distribuidoras','distribuidora','{google_places}'),
('fornecedor food service','Distribuidoras','distribuidora','{google_places}'),
('central de abastecimento','Distribuidoras','distribuidora','{google_places}'),
('distribuidora atacadista','Atacadistas / Atacarejo','atacado','{google_places}'),
('atacadista de café','Atacadistas / Atacarejo','atacado','{google_places}'),
('atacado de café','Atacadistas / Atacarejo','atacado','{google_places}'),
('atacado de alimentos','Atacadistas / Atacarejo','atacado','{google_places}'),
('atacado de bebidas','Atacadistas / Atacarejo','atacado','{google_places}'),
('cash and carry','Atacadistas / Atacarejo','atacado','{google_places}'),
('atacarejo','Atacadistas / Atacarejo','atacado','{google_places}'),
('supermercado atacado','Atacadistas / Atacarejo','atacado','{google_places}'),
('empório atacadista','Atacadistas / Atacarejo','atacado','{google_places}'),
('revenda de café','Atacadistas / Atacarejo','atacado','{google_places}'),
('café para revenda','Atacadistas / Atacarejo','atacado','{google_places}'),
('torrefação de café','Café e Torrefações','distribuidora','{google_places}'),
('torrefadora de café','Café e Torrefações','distribuidora','{google_places}'),
('indústria de café','Café e Torrefações','distribuidora','{google_places}'),
('fábrica de café','Café e Torrefações','distribuidora','{google_places}'),
('micro torrefação','Café e Torrefações','distribuidora','{google_places}'),
('torra artesanal','Café e Torrefações','distribuidora','{google_places}'),
('café especial','Café e Torrefações','distribuidora','{google_places}'),
('café gourmet','Café e Torrefações','distribuidora','{google_places}'),
('café premium','Café e Torrefações','distribuidora','{google_places}'),
('café em grão','Café e Torrefações','distribuidora','{google_places}'),
('café torrado','Café e Torrefações','distribuidora','{google_places}'),
('café moído','Café e Torrefações','distribuidora','{google_places}'),
('beneficiadora de café','Café e Torrefações','distribuidora','{google_places}'),
('rebeneficiadora de café','Café e Torrefações','distribuidora','{google_places}'),
('cooperativa de café','Café e Torrefações','distribuidora','{google_places}'),
('armazém de café','Café e Torrefações','distribuidora','{google_places}'),
('trading de café','Café e Torrefações','distribuidora','{google_places}'),
('padaria','Padarias e Confeitarias','padaria','{google_places}'),
('padaria e confeitaria','Padarias e Confeitarias','padaria','{google_places}'),
('panificadora','Padarias e Confeitarias','padaria','{google_places}'),
('padaria artesanal','Padarias e Confeitarias','padaria','{google_places}'),
('padaria gourmet','Padarias e Confeitarias','padaria','{google_places}'),
('padaria premium','Padarias e Confeitarias','padaria','{google_places}'),
('padaria industrial','Padarias e Confeitarias','padaria','{google_places}'),
('confeitaria','Padarias e Confeitarias','padaria','{google_places}'),
('doceria','Padarias e Confeitarias','padaria','{google_places}'),
('casa de bolos','Padarias e Confeitarias','padaria','{google_places}'),
('panificação','Padarias e Confeitarias','padaria','{google_places}'),
('rede de padarias','Padarias e Confeitarias','padaria','{google_places}'),
('cafeteria','Cafeterias','cafeteria','{google_places}'),
('coffee shop','Cafeterias','cafeteria','{google_places}'),
('cafeteria artesanal','Cafeterias','cafeteria','{google_places}'),
('cafeteria premium','Cafeterias','cafeteria','{google_places}'),
('cafeteria de shopping','Cafeterias','cafeteria','{google_places}'),
('casa de café','Cafeterias','cafeteria','{google_places}'),
('rede de cafeterias','Cafeterias','cafeteria','{google_places}'),
('restaurante','Restaurantes','restaurante','{google_places}'),
('restaurante por quilo','Restaurantes','restaurante','{google_places}'),
('restaurante self service','Restaurantes','restaurante','{google_places}'),
('self service','Restaurantes','restaurante','{google_places}'),
('restaurante executivo','Restaurantes','restaurante','{google_places}'),
('churrascaria','Restaurantes','restaurante','{google_places}'),
('pizzaria','Restaurantes','restaurante','{google_places}'),
('hamburgueria','Restaurantes','restaurante','{google_places}'),
('restaurante corporativo','Cozinha Industrial / Food Service','cozinha_industrial','{google_places}'),
('restaurante industrial','Cozinha Industrial / Food Service','cozinha_industrial','{google_places}'),
('buffet','Cozinha Industrial / Food Service','cozinha_industrial','{google_places}'),
('buffet corporativo','Cozinha Industrial / Food Service','cozinha_industrial','{google_places}'),
('catering','Cozinha Industrial / Food Service','cozinha_industrial','{google_places}'),
('empresa de catering','Cozinha Industrial / Food Service','cozinha_industrial','{google_places}'),
('alimentação coletiva','Cozinha Industrial / Food Service','cozinha_industrial','{google_places}'),
('empresa de alimentação','Cozinha Industrial / Food Service','cozinha_industrial','{google_places}'),
('refeitório','Cozinha Industrial / Food Service','cozinha_industrial','{google_places}'),
('refeição coletiva','Cozinha Industrial / Food Service','cozinha_industrial','{google_places}'),
('cozinha industrial','Cozinha Industrial / Food Service','cozinha_industrial','{google_places}'),
('cozinha corporativa','Cozinha Industrial / Food Service','cozinha_industrial','{google_places}'),
('operador food service','Cozinha Industrial / Food Service','cozinha_industrial','{google_places}'),
('lanchonete','Lanchonetes / Alto consumo','lanchonete','{google_places}'),
('sorveteria','Lanchonetes / Alto consumo','lanchonete','{google_places}'),
('açaíteria','Lanchonetes / Alto consumo','lanchonete','{google_places}'),
('casa de sucos','Lanchonetes / Alto consumo','lanchonete','{google_places}'),
('hotel','Hotéis e Hospitalidade','cozinha_industrial','{google_places}'),
('hotel executivo','Hotéis e Hospitalidade','cozinha_industrial','{google_places}'),
('hotel fazenda','Hotéis e Hospitalidade','cozinha_industrial','{google_places}'),
('resort','Hotéis e Hospitalidade','cozinha_industrial','{google_places}'),
('pousada','Hotéis e Hospitalidade','cozinha_industrial','{google_places}'),
('hostel','Hotéis e Hospitalidade','cozinha_industrial','{google_places}'),
('apart hotel','Hotéis e Hospitalidade','cozinha_industrial','{google_places}'),
('rede hoteleira','Hotéis e Hospitalidade','cozinha_industrial','{google_places}'),
('supermercado','Supermercados e Varejo','varejo','{google_places}'),
('hipermercado','Supermercados e Varejo','varejo','{google_places}'),
('mercado','Supermercados e Varejo','varejo','{google_places}'),
('loja de conveniência','Supermercados e Varejo','varejo','{google_places}'),
('conveniência','Supermercados e Varejo','varejo','{google_places}'),
('rede de supermercados','Supermercados e Varejo','varejo','{google_places}'),
('posto de gasolina','Supermercados e Varejo','varejo','{google_places}'),
('rede de postos','Supermercados e Varejo','varejo','{google_places}'),
('mini mercado','Mini mercado / Mercearia','mini_mercado','{google_places}'),
('mercado de bairro','Mini mercado / Mercearia','mini_mercado','{google_places}'),
('mercadinho','Mini mercado / Mercearia','mini_mercado','{google_places}'),
('mercearia','Mini mercado / Mercearia','mini_mercado','{google_places}'),
('armazém','Mini mercado / Mercearia','mini_mercado','{google_places}'),
('mercadinho de condomínio','Mercadinho de Condomínio','mercadinho_condominio','{google_places}'),
('mercado autônomo de condomínio','Mercadinho de Condomínio','mercadinho_condominio','{google_places}'),
('empório','Empório','emporio','{google_places}'),
('empório gourmet','Empório','emporio','{google_places}'),
('hortifruti','Hortifruti','hortifruti','{google_places}'),
('sacolão','Hortifruti','hortifruti','{google_places}'),
('quitanda','Hortifruti','hortifruti','{google_places}'),
('comprador de café','Compradores (cargo — fora do mapa)',NULL,'{web}'),
('comprador food service','Compradores (cargo — fora do mapa)',NULL,'{web}'),
('comprador horeca','Compradores (cargo — fora do mapa)',NULL,'{web}'),
('gerente de compras','Compradores (cargo — fora do mapa)',NULL,'{web}'),
('coordenador de compras','Compradores (cargo — fora do mapa)',NULL,'{web}'),
('supervisor de compras','Compradores (cargo — fora do mapa)',NULL,'{web}'),
('analista de compras','Compradores (cargo — fora do mapa)',NULL,'{web}'),
('central de compras','Compradores (cargo — fora do mapa)',NULL,'{web}'),
('departamento de compras','Compradores (cargo — fora do mapa)',NULL,'{web}'),
('buyer food service','Compradores (cargo — fora do mapa)',NULL,'{web}'),
('buyer horeca','Compradores (cargo — fora do mapa)',NULL,'{web}'),
('procurement manager','Compradores (cargo — fora do mapa)',NULL,'{web}'),
('fornecedor de café para restaurante','Intenção B2B (fora do mapa)',NULL,'{web}'),
('fornecedor de café para hotel','Intenção B2B (fora do mapa)',NULL,'{web}'),
('fornecedor de café para padaria','Intenção B2B (fora do mapa)',NULL,'{web}'),
('fornecedor de café para cafeteria','Intenção B2B (fora do mapa)',NULL,'{web}'),
('fornecedor de café corporativo','Intenção B2B (fora do mapa)',NULL,'{web}'),
('café para empresas','Intenção B2B (fora do mapa)',NULL,'{web}'),
('café para escritórios','Intenção B2B (fora do mapa)',NULL,'{web}'),
('café para revenda','Intenção B2B (fora do mapa)',NULL,'{web}'),
('café para distribuição','Intenção B2B (fora do mapa)',NULL,'{web}'),
('café para horeca','Intenção B2B (fora do mapa)',NULL,'{web}')
ON CONFLICT (group_name, term) DO NOTHING;
